version: 2
jobs:
    build:
      working_directory: ~/tmp
      docker:
        - image: circle/node:6
      steps:
        - checkout
        - run: npm install
        - run: npm lint
        - run: npm test